# Generated by Django 5.2.1 on 2025-07-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'contact_number')},
        ),
    ]
