# Generated by Django 5.2.1 on 2025-07-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'contact_number')},
        ),
    ]
