# Generated by Django 5.2.4 on 2025-07-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_organization_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('business_agent', 'Revenue\xa0Partner'), ('manager', 'Manager'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
