version: '3.4'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/www/med/staticfiles/
      - mediafiles:/www/med/media/
    ports:
      - 8585:80       # changed from 8282
      - 8643:443      # changed from 8443
    command: sh -c "wait-for-it -t 30 app:8000 -- nginx -g 'daemon off;'"
    depends_on:
      - app
    restart: on-failure
    networks:
      - main
    env_file:
      - .env

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: on-failure
    networks:
      - main
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    command: ./entrypoint.sh
    image: pharmacy-django
    networks:
      - main
    ports:
      - 8732:8000     # changed from 7632
    volumes:
     - ./:/usr/src/app
     - staticfiles:/usr/src/app/staticfiles
     - mediafiles:/usr/src/app/media
    restart: on-failure
    env_file:
      - .env

networks:
  main:

volumes:
  staticfiles:
  mediafiles:
  postgresql-data: