# Generated by Django 5.2.1 on 2025-06-03 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.batch'),
        ),
    ]
