# Generated by Django 5.2.1 on 2025-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_inventory_alter_order_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
