# Generated by Django 5.2.1 on 2025-06-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_customerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
