# Generated by Django 5.2.4 on 2025-08-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_checkoutorder_customer_checkoutorder_due_amount_and_more'),
        ('users', '0008_organization_is_active_organization_is_printable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.organization'),
        ),
    ]
