# Generated by Django 5.2 on 2025-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('batch_number', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=20, null=True)),
                ('shelf_no', models.CharField(default=None, max_length=10, null=True)),
                ('unit_size', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('alert_quantity', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('strips_per_box', models.PositiveIntegerField(default=0)),
                ('pieces_per_strip', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('stock_alert_qty', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=80, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('strips_per_box', models.PositiveIntegerField(default=0)),
                ('pieces_per_strip', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitPriceMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('item', models.PositiveIntegerField(default=1)),
                ('unit_size', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
            ],
        ),
    ]
