# Generated by Django 5.2 on 2025-06-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organization'),
        ),
        migrations.AddField(
            model_name='batch',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.genericname'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medicine'),
        ),
        migrations.AddField(
            model_name='unitpricemedicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_prices', to='inventory.medicine'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['name'], name='inventory_m_name_7f2fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='inventory_m_generic_6ecb74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'organization')},
        ),
    ]
