# Generated by Django 5.2.1 on 2025-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_medicine_category_alter_medicine_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pieces_per_box',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
