# Generated by Django 5.2.1 on 2025-07-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_medicine_pieces_per_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
