# Generated by Django 5.2.4 on 2025-08-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medicine_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-updated_at']},
        ),
    ]
