# Generated by Django 5.2.4 on 2025-08-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='pieces_per_strip',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='strips_per_box',
        ),
    ]
