# Generated by Django 5.2.4 on 2025-08-06 12:42

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_enable_pg_trgm'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicine',
            name='inventory_m_name_7f2fd2_idx',
        ),
        migrations.AddIndex(
            model_name='genericname',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='genericname_name_gin_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='medicine_name_gin_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
