# Generated by Django 5.2.1 on 2025-07-03 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='organization',
            field=models.ForeignKey(help_text='Organization that owns this supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.organization'),
        ),
    ]
