# Generated by Django 5.2.4 on 2025-07-29 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_organization'),
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount paid in this transaction.', max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the payment was made.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for the payment (e.g., transaction ID, payment method).', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payment_records', to='users.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='supplier.supplier')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
