# Generated by Django 5.2.4 on 2025-08-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplierpaymentrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'ordering': ['-order_date']},
        ),
    ]
